// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kayxgsnadhgpgkniouwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtheXhnc25hZGhncGdrbmlvdXdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA1NjkyOTIsImV4cCI6MjA5NjE0NTI5Mn0.AM1J1eLdmyafBNiPmD4jXKsmDF9GrgHHSmLCliSaQDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});